spring:
  cloud.loadbalancer.ribbon.enabled: false
  application:
    name: "eventarz-gateway"

eureka:
  instance:
    preferIpAddress: true

server:
  error:
    includeMessage: always

management:
  endpoint.health.show-details: always
  health:
    circuitbreakers.enabled: true
    retries.enabled: true

resilience4j:
  circuitbreaker:
#   This and the similar setting under retry makes an open circuit breaker fail before retry has a go, which is good.
#   Also means that it counts a retry as one request, no matter how many it actually tried, so I lowered request counts here.
    circuitBreakerAspectOrder: 1
    configs:
      default:
        registerHealthIndicator: true
#       In seconds for slidingWindowType: TIME_BASED
        slidingWindowSize: 60
        permittedNumberOfCallsInHalfOpenState: 1
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 50s
        failureRateThreshold: 60
#       FeignException can mean a 404, which is not a failure, like the result of checkIfUsernameExists.
#       On the other hand a failure to connect is also a FeignException, and Resilience4j can't distinguish them.
#       Solved through a wrapper that translates "retryable" exceptions to a different type.
        ignoreExceptions:
           - feign.FeignException
    instances:
      UsersClientCircuitBreaker:
        baseConfig: default
      EventsClientCircuitBreaker:
        baseConfig: default
      GroupsClientCircuitBreaker:
        baseConfig: default
  retry:
    retryAspectOrder: 2
    configs:
      default:
        registerHealthIndicator: true
        maxAttempts: 2
        waitDuration: 5s
        ignoreExceptions:
          - feign.FeignException
    instances:
      UsersClientRetry:
        baseConfig: default
      EventsClientRetry:
        baseConfig: default
      GroupsClientRetry:
        baseConfig: default

logging:
  pattern:
#    Simplified logging pattern without PID, thread name and logger name to make it readable on screenshots
    console: "${CONSOLE_LOG_PATTERN:%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}"
  level:
    com.agh.EventarzGateway.feignClients.UsersClient: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: BASIC
